name: Auto-move project items

on:
  issues:
    types: [closed]
  pull_request:
    types: [closed]

jobs:
  move-to-done:
    runs-on: ubuntu-latest
    steps:
      - name: Move card to Done
        uses: peter-evans/project-card-action@v1
        with:
          project-url: https://github.com/DairyMuffin/caa/projects/2
          column: Done
          card-id: ${{ github.event.issue.number || github.event.pull_request.number }}
